@devHost = http://localhost:3000/offline
@cloudHost = https://cofd8bq5n1.execute-api.us-east-1.amazonaws.com/dev
@host = {{devHost}}
@baseUrl = {{host}}

# @token = {{loginAPI.response.body.token}}
@token = {{login.response.body.access_token}}


###################################################################################
####################################### Auth ######################################
###################################################################################

### Sign In
# @name login
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
  "email": "john-snow@muzic.com",
  "password": "password123"
}

### Sign Up
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "name": "John Snow",
  "email": "john-snow@muzic.com",
  "password": "password123"
}

###################################################################################
####################################### Users #####################################
###################################################################################

### All Users
GET {{baseUrl}}/users
Accept: application/json

### Get Me
GET {{baseUrl}}/users/me
Accept: application/json
Authorization: Bearer {{token}}

### User by ID
GET {{baseUrl}}/users/f424f640-ab41-4481-a6fc-893adf0cc3ab
Accept: application/json

### Create User
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Kate Perry",
  "email": "kate-perry@muzic.com"
}
###################################################################################
###################################### Pages ######################################
###################################################################################

### Page by Slug
GET {{baseUrl}}/pages/slug/perry
Accept: application/json

### Page by ID
GET {{baseUrl}}/pages/3d2dbdea-19dd-494d-99d8-82c820127537
Accept: application/json

#### Create Page
POST {{baseUrl}}/pages
Content-Type: application/json

{
  "slug": "perry",
  "userId": "001b8846-274e-4aa0-9906-f5efc9f83764",
  "name": "Kate Perry"
}