service: muzic-backend

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256
  region: "us-east-1"
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(src/users/resources/muzic-users-table-iam.yml):UsersTableIAM}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /hello
      - http:
          method: ANY
          path: "{proxy+}"
    environment:
      MUZIC_USERS_TABLE: MuzicUsersTable-${opt:stage, 'dev'}      
    dependsOn:
      - UsersTable

resources:
  Resources:
    UsersTable: ${file(src/users/resources/muzic-users-table.yml):UsersTable}

custom:
  UsersTable:
    name: !Ref UsersTable
    arn: !GetAtt UsersTable.Arn
