service: muzic-backend

useDotenv: true

plugins:
  - serverless-dynamodb
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256
  region: "us-east-1"
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    DYNAMO_ENDPOINT: ${env:DYNAMO_ENDPOINT}
  iamRoleStatements:
    - ${file(src/users/resources/muzic-users-table-iam.yml):UsersTableIAM}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /hello
      - http:
          method: ANY
          path: "{proxy+}"
    environment:
      MUZIC_USERS_TABLE: MuzicUsersTable-${opt:stage, 'dev'}
    dependsOn:
      - UsersTable

resources:
  Resources:
    UsersTable: ${file(src/users/resources/muzic-users-table.yml):UsersTable}

custom:
  UsersTable:
    name: !Ref UsersTable
    arn: !GetAtt UsersTable.Arn

  dynamodb:
    stages:
      - offline
    start:
      docker: true
      port: 8080
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true
    seed:
      offline:
        sources:
          - table: MuzicUsersTable-offline
            sources: [./src/users/seeds/users.seed.json]